layout_spectrum: 0
name: Shaun Gill
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.7340425
color:
  brandStrength: 0.1032541
  lightness: 0.3322904
  saturation: 0.1633292
  rhythmicContrast: 0.3861076
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
