layout_spectrum: 0
typography_spectrum: 1
color:
  lightness: 0.8441802
  brandStrength: 0.2750619
  saturation: 0.1470588
  rhythmicContrast: 0.5489644
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Shaun Gill
